### ISSUE TITLE
Zod Schema Provider

### ISSUE THREAD

**Issue by logaretm** [formwerkjs/formwerk#44]

**Comment by DamianGlowala** [comment]
@logaretm is this still true? :)
https://formwerk.dev/guides/forms/validation/#standard-schema-validation
![Image](https://github.com/user-attachments/assets/0d6a04b3-66c8-432d-a606-1095c3dc7f40)

**Comment by logaretm** [comment]
@DamianGlowala nope, it is already supported for sometime now.

Feel free to PR it in the docs repo, I will do it later tonight if not.
