### ISSUE TITLE
Plan to incorporate Devtools?

### ISSUE THREAD

**Issue by genu** [formwerkjs/formwerk#85]
**Is your feature request related to a problem? Please describe.**
I found the dev tools in vee-validate very helpful. Are there plans to incorporate something similar in Formwerk?

**Describe the solution you'd like**
Devtools to see active forms/fields and their state

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by logaretm** [comment]
Absolutely, this is in the roadmap. I will be publishing it as soon as I can around the weekend.

I will also create an issue t
detailing the scope.

**Comment by logaretm** [comment]
closing in order to track in #86
