### ISSUE TITLE
Type error `Property '"~standard"' is missing ...` when initializing useForm with a zod schema

### ISSUE THREAD

**Issue by boussadjra** [formwerkjs/formwerk#93]
**Describe the bug**

 The error `Property '"~standard"' is missing in type 'ZodObject<{ username: ZodString; password: ZodString; }, "strip", ZodTypeAny, { username: string; password: string; }, { username: string; password: string; }>' but required in type 'GenericFormSchema'.` occurs when initializing the form with useForm using authSchema.

**To Reproduce**
 Declaring a schema and using it in the `useForm` composable: 

```js
const authSchema = z.object({
  username: z.string(),
  password: z.string().
})

const { handleSubmit } = useForm({
  schema: authSchema,
})

```

**Expected behavior**

The form should initialize without any type errors, and the `authSchema `should be correctly recognized by `useForm`.

 - OS:  windows 11
 - Editor : VSCode
 - Formwerk version : 0.5.0

**Comment by logaretm** [comment]
Which version of Zod are you using? Zod's standard schema support is only present in 3.24 any older Zod versions are not supported.

**Comment by boussadjra** [comment]
I was using Zod version `3.23.8`, I upgraded it and it works fine now. Thanks
